### ISSUE TITLE
Last changes by OlehL

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_snippets#1]
+ new command Install VS Snippets... - you can install snippets from the VS Code Marketplace.
+ new command Delete snippet markers - clear all markers in current editor tab
+ rework snippets engine for support VS snippets.
+ now you can insert snippet in another snippet.
+ improve work with placeholders. Now placeholders can be nested.

**Comment by JairoMartinezA** [comment]
Using Windows 10 after install from GH, the option **Addons Manager: Install VS snippets** don't show anything, the console also no show errors. 😕

**Comment by JairoMartinezA** [comment]
I can get this error now:

    File "C:\Users\Jairo Martinez\Downloads\Apps\Cudatext\py\cuda_snippets\snip\loader.py", line 141, in load_snippets
        for folder in os.scandir(vs_dir):
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Jairo Martinez\\Downloads\\Apps\\Cudatext\\data\\snippets_vs'

I will create manually the folder and I'll see what happens.

**Comment by JairoMartinezA** [comment]
I could run finally the option. My only concern is when I am looking for "java" by example, the list blinks each time, at the end I could understand that the plugin is searching and each time paints the results, I don't know if we can do something with this "blink" or maybe is the default way to paint the results.

**Comment by Alexey-T** [comment]
@OlehL do we need to make folder, and missed it?
You can use os.mkdir.

>FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Jairo Martinez\\Downloads\\Apps\\Cudatext\\data\\snippets_vs'

**Comment by OlehL** [comment]
fixed bug with folder in fe43996

**Comment by Alexey-T** [comment]
> I could run finally the option. My only concern is when I am looking for "java" by example, the list blinks each time, at the end I could understand that the plugin is searching and each time paints the results, I don't know if we can do something with this "blink" or maybe is the default way to paint the results.

@OlehL

**Comment by OlehL** [comment]
Reworked search. Test pls...

**Comment by Alexey-T** [comment]
It works Ok, good.

**Comment by JairoMartinezA** [comment]
Really like the new way creating cache snippets. Excellent!!!

**Comment by Alexey-T** [comment]
Released
