### ISSUE TITLE
Dlg to configure lexers

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_snippets#10]
![Screenshot from 2020-10-08 10-19-25](https://user-images.githubusercontent.com/4154978/95427208-daa14300-094f-11eb-8001-7c120686a4db.png)

Wishes

- дать двум листам отступ от краев - property "sp_a": 4
- дать свой титул - "Setup snippet lexer(s)"
- кнопка скромненькая очень

@kvichans мы тут тестим.

**Comment by kvichans** [comment]
А как это вызывать?

**Comment by Alexey-T** [comment]
Длг показывается после выбора набора в "plugins / snippets / Install VS snippets".

**Comment by kvichans** [comment]
Без меня

**Comment by OlehL** [comment]
fixed in 462d129
