### ISSUE TITLE
Two options to install VSCode snippets...

### ISSUE THREAD

**Issue by JairoMartinezA** [OlehL/cuda_snippets#17]
Hi @OlehL 

Could you help me to validate this pic?

![Snipaste_2020-10-08_17-50-32](https://user-images.githubusercontent.com/5806694/95521560-730ae800-098f-11eb-83a6-9209eaa8d86a.png)

I don't know @Alexey-T if is convenient to duplicate the option?

**Comment by Alexey-T** [comment]
I did it, made duplicated command. see plugin's install.inf file. Its ok IMO.
#4
