### ISSUE TITLE
Trying to install snippet crash with error

### ISSUE THREAD

**Issue by JairoMartinezA** [OlehL/cuda_snippets#18]
Hi @OlehL 

I am trying to install *AutoHotkey 0.2.2* but I am getting this error in console

    Traceback (most recent call last):
      File "C:\Users\Jairo Martinez\Downloads\Apps\Cudatext\py\cuda_snippets\__init__.py", line 86, in install_vs_snip
        self.do_load_snippets()
      File "C:\Users\Jairo Martinez\Downloads\Apps\Cudatext\py\cuda_snippets\__init__.py", line 18, in do_load_snippets
        self.snippets, self.glob = load_snippets(base_dir)
      File "C:\Users\Jairo Martinez\Downloads\Apps\Cudatext\py\cuda_snippets\snip\loader.py", line 164, in load_snippets
        _snips = parse_vs_snippets_file(fp, lexs)
      File "C:\Users\Jairo Martinez\Downloads\Apps\Cudatext\py\cuda_snippets\snip\loader.py", line 27, in parse_vs_snippets_file
        t = v['body']
    KeyError: 'body'

After that If I launch the **Install snippet...** option again, Cud freeze for a while and then shows directly:
![Snipaste_2020-10-08_18-04-51](https://user-images.githubusercontent.com/5806694/95522801-b3b83080-0992-11eb-865d-f7f9149212cf.png)

**Comment by Alexey-T** [comment]
Yes, on installing this "autohotkey" I dont see error, but Cud shows in status:
Installing: Python 2020.9.nnnnn

**Comment by Alexey-T** [comment]
@OlehL 
homepage of AHK snipps:
https://github.com/stef-levesque/vscode-autohotkey/blob/master/snippets/ahk.json

after 50% of file we have no "body" key in json
```
"Cancel": {
      "prefix": "Cancel",
      "body": "Cancel"
    },
    "Abort": {
      "prefix": "Abort",
      "body": "Abort"
    },
    "Retry": {
      "prefix": "Retry",
      "body": "Retry"
    },
    "Ignore":
    {
      "trigger": "Ignore",
      "contents": "Ignore"
    },
```

**Comment by OlehL** [comment]
fixed, try now

**Comment by Alexey-T** [comment]
fixed.

**Comment by OlehL** [comment]
not full fix

**Comment by Alexey-T** [comment]
My fix in #21

**Comment by OlehL** [comment]
added this fix

**Comment by Alexey-T** [comment]
@OlehL Pls close.
