### ISSUE TITLE
Command "Open issues page for VSCode snippets"

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_snippets#20]
package.json has the GH link (always? don't know)
https://github.com/stef-levesque/vscode-autohotkey/blob/master/package.json

So good to have SUBJ 

- I want to examine why we have duplicates, or why some snippet body is bad... etc.
- And to write it on GH
@OlehL

**Comment by Alexey-T** [comment]
Im not sure what list of snips to show for this cmd. List of all snips (in marketplace)? list of installed snips? better- installed snips. and not reload marketplace.

**Comment by OlehL** [comment]
todo

**Comment by OlehL** [comment]
I already added links to config.json (need old packages install again for update config.json).
I'll create Dlg for show all installed VS snippets later.
