### ISSUE TITLE
Setup snippet lexer(s) needs validate one selection

### ISSUE THREAD

**Issue by JairoMartinezA** [OlehL/cuda_snippets#23]
Hi @OlehL

After the selection of the snippet to download, the plugin shows the next dialog:

![image](https://user-images.githubusercontent.com/5806694/95680667-f94a4880-0ba0-11eb-98c8-ee43f0695230.png)

If I press **Esc** the process is aborted but if I press the OK button and I have no selected any language (To link with downloading snippet) the plugin downloads the snippet but it remains un-callable (Is not linked to a any language), I think the plugin needs to inform to the user this situation or not continue with the process until the user select at least one language.

Additional add Cancel button to this dialog.

**Comment by Alexey-T** [comment]
@OlehL I agree...

**Comment by Alexey-T** [comment]
@OlehL 
patch!

dlg_lexers_compare.py
```
    def press_ok(self, *args, **kwargs):
        # edit data dict
        files = self.data.get('files', {})
        new = {}
        for k, v in self.state.items():
            for n, i in enumerate(v.split(';')[1].split(',')):
                if i == '1':
                    lexer = self.lexers[n]
                    lx: list = new.get(lexer, [])
                    for x in files[k]:
                        if x not in lx:
                            lx.append(x)
                    new[lexer] = lx

        if not new:
            ct.msg_box('You must check at least one CudaText lexer, for snippets to work', 
                ct.MB_OK+ct.MB_ICONWARNING)
            return

        self.data['files'] = new
        # install
        path = os.path.join(ct.app_path(ct.APP_DIR_DATA), 'snippets_vs')
        vs.install_vs_snips(path, self.data)
        ct.dlg_proc(self.h, ct.DLG_HIDE)
```

**Comment by Alexey-T** [comment]
Posted PullReq.

**Comment by JairoMartinezA** [comment]
I was thinking the most intuitive friendly usage is not enable OK button until one selection is made, just for consideration 😑
