### ISSUE TITLE
paste handler?

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_snippets#3]
> и обработчик вставки текста с буффера обмена.

В Куд же есть on_paste event. поясни что именно нужно дать.
@OlehL

**Comment by OlehL** [comment]
> В Куд же есть on_paste event

Недосмотрел.  Нужно держать марки на своих местах когда пользователь вставляет кусок текста из буфера обмена.

**Comment by Alexey-T** [comment]
Это и при любой работе с марками нужно наверно. проверю

**Comment by OlehL** [comment]
Да, било би хорошо если вставку с буфера обрабатывало само ядро.  Для марок с поиска (Mark All) оно и так уже умеет это делать.
