### ISSUE TITLE
UI of search of VS snippets

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_snippets#5]
Когда я ищу по слову java  то лезет много лишнего-

![Screenshot from 2020-10-05 22-10-44](https://user-images.githubusercontent.com/4154978/95121620-fa6e1680-0757-11eb-81ee-4a82ec870532.png)

и еще лезет все про javascript. и еще лезет по описанию.
соотв-но, такой виш -

- дать чекбокс "By title" (default on- искать)
- дать чекбокс "By description" (default off- не искать)
- для отcечения javascript от java, и для языка D (где вообще дофига всего c D) - чекбокс "Whole words"

**Comment by Alexey-T** [comment]
@OlehL кстати ты не подписан на репо.

**Comment by OlehL** [comment]
Сейчас поиск работает как на маркетплейс. Согласен, что лезет много лишнего. Переделаю.

**Comment by OlehL** [comment]
Переделал диалог поиска.
Добавил опции поиска, Сейчас поиск будет работать без запросов на сервер. Заодно и решилась проблема з миганием списка.

PS. @Alexey-T  Я здесь сделал реализацию fuzzy search (как в sublime). Может такой же использовать для диалога command palette  и других?

**Comment by Alexey-T** [comment]
Отлично
Потестил, для  java, для D c whole-words. OK

**Comment by Alexey-T** [comment]
>Может такой же использовать для диалога command palette и других?

Как это такой же? у меня код fuzzy search на паскале, как это я сделаю такой же? мой код работает ок.

**Comment by OlehL** [comment]
![image](https://user-images.githubusercontent.com/26593946/95431900-99f8f800-0956-11eb-918f-197ea2b44b08.png)
![image](https://user-images.githubusercontent.com/26593946/95431941-a5e4ba00-0956-11eb-8811-13ed4e37e8d2.png)
Я имел в виду только подход к поиску. У меня больший приоритет имеют совпадение пар и по этому поиск работает более точно. Твой код работает отлично, но иногда находит не то что нужно пользователю.

**Comment by Alexey-T** [comment]
Хорошо,видимо надо так делать.

**Comment by OlehL** [comment]
Здесь закрою
