### ISSUE TITLE
Java snippets (VScode) - many dup names

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_snippets#6]
![Screenshot from 2020-10-05 22-20-01](https://user-images.githubusercontent.com/4154978/95122334-03131c80-0759-11eb-9f14-036e76d8825f.png)

x1, x2, y1, y2, и повторены много раз.

![Screenshot from 2020-10-05 22-23-02](https://user-images.githubusercontent.com/4154978/95122538-58e7c480-0759-11eb-90f5-c5c1d16da8be.png)

A0, A1, A2.... и тоже повторены.

@OlehL

**Comment by OlehL** [comment]
Какое название этого пакета сниппетов?

**Comment by Alexey-T** [comment]
Java snippets 0.0.1

**Comment by OlehL** [comment]
![image](https://user-images.githubusercontent.com/26593946/95431296-a03aa480-0955-11eb-93c9-305814e2cbd1.png)
см. сам, там в json так сниппеты сделаны.

**Comment by Alexey-T** [comment]
Да, вижу, пока ничего не сделать
