### ISSUE TITLE
Py relative imports

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_snippets#7]
В Пи3 есть relative imports-

`from . import timer`

для файла в текущ. папке.
надо бы юзать это. так красиво.
для импорта vs/* из ui/* придется писать
`from ..vs import vs` - некрасиво.

предлагаю. 

- все Пи файлы свалить в корень, убрать все папки
- везде юзать `from . import vs` итд
 @OlehL

**Comment by OlehL** [comment]
PEP 8 рекомендует именно абсолютный импорт.
> Relative imports for intra-package imports are highly discouraged. Always use the absolute package path for all imports. Even now that PEP 328 [7] is fully implemented in Python 2.5, its style of explicit relative imports is actively discouraged; absolute imports are more portable and usually more readable.

Кроме того абсолютный импорт мне нужен для отладки кода плагинов, так как использую PROC_EXEC_PYTHON. 
Папки vs/ и ui/ тоже думаю убрать.

**Comment by Alexey-T** [comment]
Ок. может убрать папки(все в корень) но оставить абс.импорты?

**Comment by OlehL** [comment]
Хорошо

**Comment by OlehL** [comment]
done
