### ISSUE TITLE
Wish for more snippet macros

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_snippets#8]
From @tmsg-gh

It's pretty good and I have a small suggestion. Is it possible to add two further expansion variables?

${ffname} or ${pname} -- insert full name of file (ie inc path and ext). (Ideally I would like a way to expand a) the path or b) the name or c) the ext. Perhaps something like ${fname:p}, ${fname} and ${fname:e}.)

${env:name} -- insert content of environment variable "name"

**Comment by OlehL** [comment]
Good idea.

**Comment by OlehL** [comment]
Add:

- `${fpath}` - full path with file name
- `${fdir}` - path without file name
- `${fext}` - ext
- `${psep}` - std. OS separator


${env:name} - I'll add later

**Comment by OlehL** [comment]
Add `${env:name}` in 4330f52

**Comment by Alexey-T** [comment]
Thanks! @Tmsg-gh Pls test.
